"""add_user_id_to_projects

Revision ID: c23411b5bd1a
Revises: 42de536fc118
Create Date: 2025-09-25 17:20:54.674698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23411b5bd1a'
down_revision: Union[str, None] = '42de536fc118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear un usuario por defecto si no existe
    op.execute("INSERT OR IGNORE INTO users (id, username, device_id, created_at, updated_at) VALUES (1, 'default_user', 'default_device', datetime('now'), datetime('now'))")
    
    # Agregar la columna user_id como nullable primero
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Actualizar todos los proyectos existentes para que pertenezcan al usuario por defecto
    op.execute("UPDATE projects SET user_id = 1 WHERE user_id IS NULL")
    
    # Ahora hacer la columna NOT NULL
    op.alter_column('projects', 'user_id', nullable=False)
    
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
