name: Alternative Android AAB Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npm list expo
        
    - name: Clean workspace
      run: |
        rm -rf android
        rm -rf node_modules/.cache
        rm -rf .expo
        
    - name: Export for production
      run: |
        npx expo export --platform android
        
    - name: Prebuild Android
      run: |
        npx expo prebuild --platform android --clean
        
    - name: Generate keystore
      run: |
        cd android/app
        keytool -genkeypair -v -storetype PKCS12 -keystore lifeplanner-release-key.keystore -alias lifeplanner-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass lifeplanner123 -keypass lifeplanner123 -dname "CN=LifePlanner, OU=Development, O=LifePlanner, L=City, S=State, C=US"
        
    - name: Build AAB with retry
      run: |
        cd android
        for i in {1..3}; do
          echo "Attempt $i"
          if ./gradlew bundleRelease --no-daemon --stacktrace --info; then
            echo "Build successful on attempt $i"
            break
          else
            echo "Build failed on attempt $i"
            if [ $i -eq 3 ]; then
              echo "All attempts failed"
              exit 1
            fi
            echo "Retrying in 10 seconds..."
            sleep 10
          fi
        done
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
